# Generated by Django 3.2.4 on 2021-06-10 09:11

from django.db import migrations, models
import loanManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents1',
            field=models.FileField(blank=True, null=True, upload_to=loanManagement.models.upload_documents1, verbose_name='documents1 field'),
        ),
        migrations.AlterField(
            model_name='application',
            name='documents2',
            field=models.FileField(blank=True, null=True, upload_to=loanManagement.models.upload_documents2, verbose_name='documents2 field'),
        ),
        migrations.AlterField(
            model_name='application',
            name='documents3',
            field=models.FileField(blank=True, null=True, upload_to=loanManagement.models.upload_documents3, verbose_name='documents3 field'),
        ),
    ]
