# Generated by Django 3.2.4 on 2021-06-15 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanManagement', '0006_application_accepteance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bankAuthor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
